set_property PACKAGE_PIN E3 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN A8 [get_ports reset]
    set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN C11 [get_ports speedup_disable]
    set_property IOSTANDARD LVCMOS33 [get_ports speedup_disable]

set_property PACKAGE_PIN C9 [get_ports btn_l]
    set_property IOSTANDARD LVCMOS33 [get_ports btn_l]

set_property PACKAGE_PIN B8 [get_ports btn_u]
    set_property IOSTANDARD LVCMOS33 [get_ports btn_u]
      
set_property PACKAGE_PIN D9 [get_ports btn_r]
    set_property IOSTANDARD LVCMOS33 [get_ports btn_r]

set_property PACKAGE_PIN B9 [get_ports btn_d]
        set_property IOSTANDARD LVCMOS33 [get_ports btn_d] 

# set_property PACKAGE_PIN U2 [get_ports {seg_select_out[0]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {seg_select_out[0]}]
# set_property PACKAGE_PIN U4 [get_ports {seg_select_out[1]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {seg_select_out[1]}]
# set_property PACKAGE_PIN V4 [get_ports {seg_select_out[2]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {seg_select_out[2]}]
# set_property PACKAGE_PIN W4 [get_ports {seg_select_out[3]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {seg_select_out[3]}]

# set_property PACKAGE_PIN W7 [get_ports {dec_out[0]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[0]}]
# set_property PACKAGE_PIN W6 [get_ports {dec_out[1]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[1]}]
# set_property PACKAGE_PIN U8 [get_ports {dec_out[2]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[2]}]
# set_property PACKAGE_PIN V8 [get_ports {dec_out[3]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[3]}]
# set_property PACKAGE_PIN U5 [get_ports {dec_out[4]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[4]}]
# set_property PACKAGE_PIN V5 [get_ports {dec_out[5]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[5]}]
# set_property PACKAGE_PIN U7 [get_ports {dec_out[6]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[6]}]
# set_property PACKAGE_PIN V7 [get_ports {dec_out[7]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {dec_out[7]}]

set_property PACKAGE_PIN E1 [get_ports {led_out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property PACKAGE_PIN F6 [get_ports {led_out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property PACKAGE_PIN G6 [get_ports {led_out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property PACKAGE_PIN G4 [get_ports {led_out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property PACKAGE_PIN J4 [get_ports {led_out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property PACKAGE_PIN G3 [get_ports {led_out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property PACKAGE_PIN H4 [get_ports {led_out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property PACKAGE_PIN J2 [get_ports {led_out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property PACKAGE_PIN J3 [get_ports {led_out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[8]}]
set_property PACKAGE_PIN K2 [get_ports {led_out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[9]}]
set_property PACKAGE_PIN H6 [get_ports {led_out[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[10]}]
set_property PACKAGE_PIN K1 [get_ports {led_out[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[11]}]

set_property PACKAGE_PIN E15 [get_ports {colour_out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[0]}]
set_property PACKAGE_PIN E16 [get_ports {colour_out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[1]}]
set_property PACKAGE_PIN D15 [get_ports {colour_out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[2]}]
set_property PACKAGE_PIN C15 [get_ports {colour_out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[3]}]
set_property PACKAGE_PIN J17 [get_ports {colour_out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[4]}]
set_property PACKAGE_PIN J18 [get_ports {colour_out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[5]}]
set_property PACKAGE_PIN K15 [get_ports {colour_out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[6]}]     
set_property PACKAGE_PIN J15 [get_ports {colour_out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[7]}]
set_property PACKAGE_PIN U12 [get_ports {colour_out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[8]}]
set_property PACKAGE_PIN V12 [get_ports {colour_out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[9]}]  
set_property PACKAGE_PIN V10 [get_ports {colour_out[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[10]}]
set_property PACKAGE_PIN V11 [get_ports {colour_out[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {colour_out[11]}]
    
set_property PACKAGE_PIN U14 [get_ports h_sync]
    set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
    
set_property PACKAGE_PIN V14 [get_ports v_sync]
    set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
    